### ISSUE TITLE
Concepts Unicode

### ISSUE THREAD

**Issue by boisgera** [ue12/python-advanced#2]
La notion de "caractère" est je crois assez mal définie ; on pourrait juste mettre des guillemets autour du terme pour suggérer qu'il y a un loup 😀. Selon l'interprétation donnée à ce terme l'assertion "1 caractère = 1 code point" peut vite devenir fausse.

Exemples concrets en français où le modèle commence à craquer :

    >>> "e\u0301" # 2 code points
    'é'
    >>> "\ufb00" # 1 code point
    'ﬀ'

Il y en a d'autres plus rigolos : 

    >>> flag = "🇫🇷"
    >>> len(flag)
    2
    >>> flag[0]
    '🇫'
    >>> flag[1]
    '🇷'

et je ne parle pas du thai ...

Bref, "attention, dans le détail c'est un peu plus compliqué que ça" serait un message utile à faire passer.

**Comment by parmentelat** [comment]
clairement on est là encore dans le "je vous mens pour votre bien"

donc pas de souci de mon coté pour rendre plus explicite le fait que "attention, dans le détail c'est un peu plus compliqué que ça"
