### ISSUE TITLE
Defaultdict et/ou setdefault ?

### ISSUE THREAD

**Issue by boisgera** [ue12/python-advanced#5]
Juste une remarque que je me suis faite en lisant le slide sur `defaultdict` : je ne l'ai jamais utilisé de ma vie 😀
Probablement parce que dans les uses cases concernés, j'utilise la méthode `setdefault`. Je n'ai pas réfléchi dans le détail aux pro / cons (les uses cases ne se recouvrent pas à 100%).

Tout ça pour dire que les deux mécanismes sont apparentés semblent souvent présentés en même temps, cf. par exemple <https://realpython.com/python-defaultdict/>

**Comment by parmentelat** [comment]
le sujet c'est clairement d'adresser le use case: 'mon code fait 2 lignes mais à cause de la gestion du défaut de clé il faut que j'en écrive 4, c'est pas lisible'

```
for item in collection:
     dico[item].append(foo(item))
```

devient

```
for item in collection:
    if item not in dico:
        dico[item] = []   
    dico[item].append(foo(item))
```

`setdefault` c'était la première mouture pour ça; ça doit faire 10 ans que j'ai pas utilisé ça mais de mémoire, mof c'est pas terrible, on passe de 4 à 3 lignes, la pollution reste non négligeable
en plus avec defaultdict on a une annotation plus sémantique, on dit que les values sont de type `list` ou `int` ou `tartempion`; enfin ça permet de voir par exemple que `int()` retourne 0 et que c'est normal et bien que ce soit comme ça

mais bon une fois qu'on a dit tout ça:
* oui c'est secondaire complètement comme point
* du coup je pense que de voir une seule méthode pour ce *use case* ça suffit bien

**Comment by boisgera** [comment]
> `setdefault` c'était la première mouture pour ça; ça doit faire 10 ans que j'ai pas utilisé ça mais de mémoire, mof c'est pas terrible,

C'est effectivement dégueu ; flexible mais peu lisible ; impossible de deviner ce que ça fait sans lire la doc (à chaque fois que j'en ai besoin en ce qui me concerne 😁).

> en plus avec defaultdict on a une annotation plus sémantique, on dit que les values sont de type `list` ou `int` ou `tartempion`

C'est vrai, c'est un avantage ; ça favorise un usage des listes comme collection ordonnée d'objets du même "type" (ou "nature" avec le duck typing).
