### ISSUE TITLE
Dijkstra et temps de calcul

### ISSUE THREAD

**Issue by boisgera** [ue12/python-advanced#7]
Testé avec un graphe planaire de taille modérée :

    W, H = 100, 100
    graph = {}
    for w in range(W+1):
        for h in range(H+1):
            d = {}
            graph[(w, h)] = d
            if w + 1 <= W:
                d[(w + 1, h)] = 1
            if h + 1 <= H:
                d[(w, h + 1)] = 1

Il faut ~ 30 sec à l'algo actuel de shortest distance pour me donner la réponse sur mon laptop (quand on cherche la distance entre les coins opposés). Ouch.

Sauf erreur de ma part, en mémorisant en plus des noeuds visités l'ensemble des noeuds candidats à la prochaine visite (avec un "score" temporaire de distance plus petit que l'infini), et en cherchant le meilleur de ces noeuds (par score) parmi ces seuls candidats à chaque itération, on divise ça par ~ 600 (0.05 secondes). Une astuce consiste à stocker les candidats avec leur score de distance comme valeur associée dans un dict, et à faire `best = min(dct, key=dct.get)` pour trouver le suivant. A noter que sauf erreur de ma part, dans le code actuel, outre qu'il faut filtrer les edges qui vont bien en partant de tous les edges, j'ai l'impression qu'on est amené à faire plein de calculs qu'on "jette" et qu'on refera sans doute au tour d'après ; au lieu de les stocker et de les réutiliser. 

Alternative avancée (? ; merci internet) : `heapq` est notre ami ; il peut classer en permanence les candidats par score de distance si on s'y prend bien.

**Comment by boisgera** [comment]
En profilant on voit qu'on passe 96.8% du temps passé à relister (et filtrer) tous les triplets source, destination et poids :

    Line #      Hits         Time  Per Hit   % Time  Line Contents
    ==============================================================
       100                                           @profile
       101                                           def shortest_distance1(graph, v1, v2):
       102                                           
       103         1          2.0      2.0      0.0      visited = {v1: 0}
       104                                           
       105         1          0.0      0.0      0.0      running = True
       106                                           
       107                                               while True:
       108     20400  107588581.0   5274.0     96.8          edges = {(s, d)
       109     10200       6800.0      0.7      0.0                   for s, adj in graph.items()
       110                                                            for (d, w) in adj.items()
       111                                                            if s in visited and d not in visited}
       112                                           
       113                                                   # out of luck, no path can be found
       114     10200      10946.0      1.1      0.0          if not edges:
       115                                                       return None
       116                                           
       117                                                   # find the best tuple (edge, distance)
       118     10200       9119.0      0.9      0.0          shortest_length = math.inf
       119     10200       5548.0      0.5      0.0          shortest_edge = None
       120   1371762     683438.0      0.5      0.6          for (s, d) in edges:
       121   1361562     790252.0      0.6      0.7              w = graph[s][d]
       122   1361562     765236.0      0.6      0.7              dist = visited[s] + w
       123   1361562     660070.0      0.5      0.6              if dist <= shortest_length:
       124    699927     322646.0      0.5      0.3                  shortest_length = dist
       125    699927     339321.0      0.5      0.3                  shortest_edge = (s, d)
       126                                           
       127                                                   # mark newly selected vertex
       128     10200       5061.0      0.5      0.0          best_src, best_dst = shortest_edge
       129     10200       6972.0      0.7      0.0          visited[best_dst] = shortest_length
       130                                           
       131                                                   # are we done ?
       132     10200       5335.0      0.5      0.0          if best_dst == v2:
       133         1          0.0      0.0      0.0              return shortest_length

**Comment by parmentelat** [comment]
> On 1 Aug 2021, at 22:14, Sébastien Boisgérault ***@***.***> wrote:
> 
> 
> Testé avec un graphe planaire de taille modérée :
> 
> W, H = 100, 100
> graph = {}
> for w in range(W+1):
>     for h in range(H+1):
>         d = {}
>         graph[(w, h)] = d
>         if w + 1 <= W:
>             d[(w + 1, h)] = 1
>         if h + 1 <= H:
>             d[(w, h + 1)] = 1
> 
> Il faut ~ 30 sec à l'algo actuel de shortest distance pour me donner la réponse (quand on cherche la distance entre les coins opposés). Ouch.
> 
> Sauf erreur de ma part, en mémorisant en plus des noeuds visités l'ensemble des noeuds candidats à la prochaine visite (avec un "score" temporaire de distance plus petit que l'infini), et en cherchant le meilleur de ces noeuds (par score) parmi ces seuls candiats à chaque itération, on divise ça par ~ 600 (0.05 secondes). Une astuce consiste à stocker les candidats avec leur score de distance comme valeur associée dans un dict, et à faire best = min(dct, dct.get) pour trouver le suivant. A noter que sauf erreur de ma part, dans le code actuel, outre qu'il faut filtrer les edges qui vont bien en partant de tous les edges, j'ai l'impressio qu'on est amené à faire plein de calculs qu'on "jette" et qu'on refera sans doute au tour d'après ; au lieu de les stocker et de les réutiliser.
> 
> Alternative avancée (? ; merci internet) : heapq est notre ami ; il peut classer en permanence les candidats par score de distance si on s'y prend bien.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

je ne suis pas vraiment surpris

à ce stade du cours on s’efforce de manipuler les types dictionnaire et ensemble un peu en mode b-a-ba, même si dans un contexte (les algos de graphe) disons, on l’espère, un peu intéressant

donc on n’est pas dans l’hyper-optimisation

c’est clairement avec un heapq en effet qu’on pourrait améliorer ça
et d’ailleurs dans le sujet de fin de trimestre de l’an passé - le taquin - on les mettait en situation de faire ce travail d’optimisation car sinon l’algo naïf prenait des plombes et ça impactait la note; et dans ce contexte l'énoncé les pointait justement vers heapq

donc oui bien sûr c’est clairement optimisable; je suis preneur si tu sais proposer un épilogue au TP, qui optimiserait grandement sans trop défigurer le premier jet du code, qui a mon avis reste intéressant à montrer dans un premier temps (parce qu’il est simple à lire)



ps / digression

pas grand chose à voir, mais:

l’objectif du taquin (pour avoir 20) c’était iirc de résoudre une dizaine de grilles en 10 ou 15 secondes (avec un algo A*)

je me suis ensuite amusé à recoder en Rust - un prétexte pour pratiquer ça - une approche cette fois brute-force qui parcourt exhaustivement tout le graphe - on parle de 9!/2 180.000 noeuds en gros - et qui donc calcule la solution optimale de toutes les grilles (et non plus une solution approchée d’une grille) et ça prend en tout 1.8s; donc en gros 10e-5s/grille
on peut bien sûr rien en conclure (différent langage, différent algo), mais tout de même...

**Comment by boisgera** [comment]
Laissons de coté le pinaillage avec `heapq` qui est sans doute beaucoup trop avancé. Je n'aurais pas du le mentionner, c'est un red herring. Revenons au point principal ; est-ce que le code ci-dessous -- sans structure "exotique" -- est correct ?

    def shortest_distance(graph, source, target):
        graph = defaultdict(dict, graph) # optional; see comment below
        todo, done = {source: 0}, {}
        while todo:
            # find the key with minimal value in todo dict
            vertex, value = None, math.inf 
            for vertex_, value_ in todo.items():
                if value_ < value:
                    vertex, value = vertex_, value_
            # # The three lines above could be factored out;
            # # alternatively we could also do:
            # vertex = min(todo, key=todo.get) 
            # value = todo[vertex]
            if vertex == target:
                return value
            else:
                done[vertex] = value
                del todo[vertex]
                # Use `get(vertex, {})` if you don't like defaultdict
                for target_, weight in graph[vertex].items(): 
                    if target_ not in done:
                        new_value = value + weight
                        if new_value < todo.get(target, math.inf):
                            todo[target_] = new_value
        else:
            return None

Il donne les même résultats que la solution de référence sur les qq exemples que j'ai testé. Sur des exemples de taille modérée, il semble plus rapide de plusieurs ordres de grandeur (ms au lieu de s typiquement), donc on est très loin de questions d'hyper-optimisation il me semble. Attention, il est tout à fait possible que le code soit incorrect, si vous (@parmentelat , @valroy & autres) me pointez le pb du doigt je suis client !

J'ai un avis mitigé sur l'impact / la faisabilité de cette session de tp à ce stade(*) (disclaimer: j'ai jamais trop aimé l'algo 😀):

  - j'y suis depuis beaucoup trop longtemps (et j'ai accès à des ressources bien supérieures aux élèves même si je ne suis pas très malin 😁),

  - j'anticipe une session où ça va être un cauchemar de débugger le code des élèves (sauf à les guider à l'extrème, ce qui n'est pas efficace dans l'apprentissage),

  - le "style" de compétences à mettre en oeuvre me semble très différent du reste de l'enseignement so far et donc des objectifs d'apprentissage que je percevais ; le volet algo me semble largement dominer ici l'aspect "découverte & manip concrête des dicts et autres structures de données utiles". 

J'ai qq autres remarques sur le sujet à peu près sans lien avec ce qui précède, je ferai probablement d'autre issues.

++ !

Seb

(*) Je ne parle que du volet plus court chemin ; je ne vois aucun pb avec le reste ("parsing", nb de sommets, sommets atteignables, etc.)

**Comment by boisgera** [comment]
> Attention, il est tout à fait possible que le code soit incorrect, si vous (@parmentelat , @valroy & autres) me pointez le pb du doigt je suis client !

Le comportement des deux implémentations est différent sur les test cases fournis (après tweakage, je n'ai pas réussi à les faire passer out of the box), donc j'imagine qu'il y a bien un problème dans ma version :grin:.

**Comment by gschwind** [comment]
Bonjour Sébatien,

J'ai quelque commentaires:
* d’abord je trouve que l'utilisation du defaultdict n'est pas approprié et que graph.get(...) est meilleurs parce qu'il évite la copie du graphe et qu'il ne modifie pas le graphe durant la fonction, contrairement au defaultdict qui va créé un entré dans le dictionnaire a chaque acces pour les clef inexistante;
* j'ai utilisé la fonction min de maniere a un peu plus subtil que tu le propose;
* j'ai également fixé le code qui avait un faute de typo dans la ligne todo.get(target, math.inf);
* le code retourne maintenant le chemin en question.

Par ailleurs J'ai fait un benchmark et je suis a ~25 ms par chemin (incluant le print et le random) pour la recherche de chemin aléatoire dans l'arbre 100,100 ci dessus

<pre>
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import math
from collections import defaultdict

W, H = 100, 100
graph = {}
for w in range(W+1):
    for h in range(H+1):
        d = {}
        graph[(w, h)] = d
        if w + 1 <= W:
            d[(w + 1, h)] = 1
        if h + 1 <= H:
            d[(w, h + 1)] = 1

def shortest_path(graph, source, target):
    # todo and done store a tuple of (previous vertex, min weight to vertex)
    todo, done = {source: (None, 0.0)}, {}
    while todo:
        # find the key with minimal value in todo dict
        vertex, value = min(todo.items(), key=lambda v: v[1])
        if vertex == target:
            weight = value[1]
            # generate the path using previous vertex
            path = [vertex]
            while value[0] is not None:
                path.append(value[0])
                value = done[value[0]]
            return path[::-1], weight
        else:
            done[vertex] = value
            del todo[vertex]
            # update weight for all connected vertex
            for next_vertex, weight in graph.get(vertex, {}).items():
                if next_vertex in done:
                    continue
                new_weight = value[1] + weight
                new_value = todo.get(next_vertex, (vertex, math.inf))
                if new_weight < new_value[1]:
                    todo[next_vertex] = (vertex, new_weight)
    else:
        return None, math.inf

from time import monotonic_ns
from random import randrange

NSAMPLE = 1000

t0 = monotonic_ns()
for _ in range(1000):
    fr = (randrange(W), randrange(H))
    to = (randrange(W), randrange(H))
    path, w = shortest_path(graph, fr, to)
    print(f"fr: {fr}, to: {to}, weight: {w}, path: {path}")
t1 = monotonic_ns()

print("{:f} ms".format((t1-t0)/NSAMPLE*1e-6))

</pre>

**Comment by boisgera** [comment]
Salut @gschwind !

> d’abord je trouve que l'utilisation du defaultdict n'est pas approprié et que graph.get(...) est meilleurs parce qu'il évite la copie du graphe et qu'il ne modifie pas le graphe durant la fonction, contrairement au defaultdict qui va créé un entré dans le dictionnaire a chaque acces pour les clef inexistante;

Je préfère comme toi le `get` ici ; j'avais mis un `defaultdict` pour faire plaisir à @parmentelat  😉. Le sujet des patterns "avancés" de dict (tout sauf les méthodes `__getitem__` et `__setitem__` du dict de base) est apparu plusieurs fois dans les discussions (#5, #8) et ça devient vite "subtil" (au niveau des élèves) selon ce qu'on cherche à optimiser (performance, lisibilité, etc.). Et/ou largement relever de préférences personnelles.  Je pense que pédagogiquement c'est le signe qu'il ne faut pas trop se prendre la tête sur le sujet et vouloir être trop normatif. A titre personnel ça ne me semblerait pas abominable que des étudiants n'utilisent ni defaultdict, ni get, ni setdefault ; ca me semble être des connaissances utiles, mais de 2nd ordre par rapport aux autres choses à savoir faire.



> j'ai utilisé la fonction min de maniere a un peu plus subtil que tu le propose;

Vu ! Le code que j'ai écrit est effectivement un peu con (le lookup fait après qu'on ait trouvé la meilleure clé est inutile si on s'y prend bien, comme toi). J'ai un peu peur que le code final soit un peu "terse" pour les étudiants, c'est pour ça que j'avais favorisé  par défaut la version "élémentaire" (mais verbeuse).

> j'ai également fixé le code qui avait un faute de typo dans la ligne todo.get(target, math.inf);

Bien vu, je suis un boulet 🤦‍♂️ ... mais rassuré que ça ne soit pas un pb conceptuel 😁

>    le code retourne maintenant le chemin en question.

Nice, merci de t'être penché là-dessus 😀

**Comment by parmentelat** [comment]
## à propos de defaultdict

c'est juste une opportunité de montrer qu'un type permet de construire des objets
mais je le redis, c'est du troisième ordre franchement, on s'en fout

## sur le reste

comme je n'ai pas le temps de me replonger dedans là tout de suite, est-ce que quelqu'un serait assez aimable pour me résumer votre échange en 4 lignes (limite dure hein, sébastien ;-)

**Comment by valroy** [comment]
la résolution de ce problème a été faite par Ford et Dantzig - pas par Dijkstra
encore un qui sait bien se mettre en avant ...

**Comment by boisgera** [comment]
> comme je n'ai pas le temps de me replonger dedans là tout de suite, est-ce que quelqu'un serait assez aimable pour me résumer votre échange en 4 lignes (limite dure hein, sébastien ;-)

Ton code initial semble correct mais effroyablement lent, le mien est sensiblement plus rapide mais incorrect 😁. @gschwind a corrigé son erreur évidente, amélioré qq points plus subtils (et ajouté la détermination du chemin optimal). On peut éventuellement argumenter que certaines de ces optimisations rendraient le code un peu plus impénétrable aux padawans. 
**Conclusion:** adopter la version de Benoît.

(<400 caractères 😇)
