### ISSUE TITLE
Misc. TP Graphes

### ISSUE THREAD

**Issue by boisgera** [ue12/python-advanced#8]
En vrac :

  - J'ai du mal avec les questions sur les structures de données représentant un graphe de façon adaptée alors que je ne sais pas ce qu'on va faire de ce graphe (quelles opérations vont être fréquentes ? Est-ce qu'on va muter le graphe ? etc). J'ai un problème de causalité quoi, qui peut peut-être être résolu par permutation, en parlant un peu des algos / opérations avant de réfléchir aux structures de données (?).

  - (pinaillage) Je mettrais un `return dict(g)` à la fin de `parse_graph2` (l'usage de `defaultdict` est un détail interne d'implémentation, comme ça la sortie est la même que `parse_graph1` ; à noter que sur cet exemple, entre la version naive, le defaultdict et le setdefault (cf #5), je crois que je trouve la version simple la "mieux" -- plus explicite / lisible -- des trois ; YMMV of course).

  - (secondaire) pour la perf, je me disais que ça serait bien d'ajouter des graphes de référence de taille modérée (assez pour stresser l'algo) *dont les solutions de plus court chemin sont évidentes*. Je pense à des noeuds organisés linéairement avec tous le même poids et une grille de points régulièrement espacés sur un carré de taille 1, ou chaque noeud est relié à tous les autres, avec comme poids la distance euclidienne. Ce genre de trucs (je viens de voir le folder `data`, je ne l'ai pas exploré en détail, mais ça ne me semble pas couvrir ce use case).

  - (pas grave ?) quasiment tous les exemples de graphe que je génère (pour des tests) ont "naturellement" soit des valeurs flottantes (un détail ...), soit des clés qui ne sont pas des chaînes de caractères (par exemple des entiers, ou un couple de coordonnées sur une grille). Ca n'est pas dramatique (je peux les générer de façon programmatique et ou mapper la représentation des clés vers des strings), mais en l'état (à cause des strings non quoteés) le format de sérialisation ne convient pas forcément à ces uses cases. Je comprends bien que quoter les strings dans le format -- en toute généralité, en autorisant des escape sequences, etc. -- ferai exploser la difficulté du parsing (entre mega-hack ou nécessité d'intro d'autres outils). Je me demande si on ne pourrait pas autoriser des quotes en interdisant des quotes escapées de même type dedans par exemple (?) ... histoire de permettre d'écrire `"(0, 0)", "(0, 1)", 1`(oui, ça complique quand même les choses : il faut scanner les `"` ; on ne peut plus simplement splitter sur les virgules ; mais de façon modérée).
  
  - J'ai du bidouiller pour lancer les tests (tu les invoques peut-être à travers un framework qui les trouvent automatiquement @parmentelat ?). Sauf erreur (possible) ça coinçait aussi à cause des lignes blanches dans les fichiers de données (le "parsing" n'ignore pas les lignes blanches, il cale).

**Comment by parmentelat** [comment]
> J'ai du bidouiller pour lancer les tests (tu les invoques peut-être à travers un framework qui les trouvent automatiquement @parmentelat ?). Sauf erreur (possible) ça coinçait aussi à cause des lignes blanches dans les fichiers de données (le "parsing" n'ignore pas les lignes blanches, il cale).

les tests ne sont sans doute pas exécutés de manière aussi systématique que ce qu'on pourrait espérer ;)
iow ça a dû être lancé à la main un nombre de fois < 5 ...
sinon, j'utilise facilement `pytest`

**Comment by gschwind** [comment]
Bonjour,

>     * (pas grave ?) quasiment tous les exemples de graphe que je génère (pour des tests) ont "naturellement" soit des valeurs flottantes (un détail ...), soit des clés qui ne sont pas des chaînes de caractères (par exemple des entiers, ou un couple de coordonnées sur une grille). Ca n'est pas dramatique (je peux les générer de façon programmatique et ou mapper la représentation des clés vers des strings), mais en l'état (à cause des strings non quoteés) le format de sérialisation ne convient pas forcément à ces uses cases. Je comprends bien que quoter les strings dans le format -- en toute généralité, en autorisant des escape sequences, etc. -- ferai exploser la difficulté du parsing (entre mega-hack ou nécessité d'intro d'autres outils). Je me demande si on ne pourrait pas autoriser des quotes en interdisant des quotes escapées de même type dedans par exemple (?) ... histoire de permettre d'écrire `"(0, 0)", "(0, 1)", 1`(oui, ça complique quand même les choses : il faut scanner les `"` ; on ne peut plus simplement splitter sur les virgules ; mais de façon modérée).

Pour les données il ne serai pas judicieux d'utiliser le module json, plutot que de faire un parseur de teste a la main ?
<pre>
import json
with open("data.json") as f:
        d = json.load(f)
# Do some structure change.
</pre>

**Comment by boisgera** [comment]
> Pour les données il ne serai pas judicieux d'utiliser le module json, plutot que de faire un parseur de teste a la main ?

Dans le monde réel j'imagine que n'importe quelle combinaison raisonnable de format de données pré-existant et de parseur sur étagère serait bien mieux. Mais je crois que c'est ici un prétexte pour manipuler les fichiers, les lignes, les split, strip, etc. Donc je suggérai des trucs dans la continuité de ça.
